[package]
name = "tagsy"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tagsy"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
comfy-table = { workspace = true }
owo-colors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tagsy-api = { workspace = true }
tagsy-core = { workspace = true }
tagsy-ipc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
